name: Taller03

env: # ← nivel workflow (disponible en todos los jobs)
  APP_NAME: lab-github-actions
  REGISTRY: docker.io

on:
  workflow_dispatch:


jobs:
  prueba:
    name: Imprimir contexto
    runs-on: ubuntu-latest
    env:                      # ← nivel job (disponible en todos los steps del job)
      BUILD_TARGET: production

    steps:
      - name: Mostrar info
        env: # ← nivel step (solo en este step)
          STEP_VAR: valor-local
        run: |
          echo " ------------------- "
          echo "APP: $APP_NAME"
          echo "Target: $BUILD_TARGET"
          echo "Step var: $STEP_VAR"
          echo " ------------------- "
          echo "SHA: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Evento: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Runner OS: ${{ runner.os }}"
          echo " ------------------- "
